---
abstract: 'A collection of star map generation tools for the RPG Traveller'
author:
  - 'Peter L. Berghold <peter@berghold.net>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  UNIVERSAL: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPG-Traveller-Starmap
requires:
  Bit::Vector: 0
  Exporter: 0
  Moose: 0
  RPG::Dice: 0
  constant: 0
  feature: 0
  perl: 5.010001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=RPG-Traveller-Starmap
version: 0.500
